package it.unimore.wldt.test.adapter;

import it.unimore.dipi.iot.wldt.engine.WldtConfiguration;
import it.unimore.dipi.iot.wldt.engine.WldtEngine;
import it.unimore.dipi.iot.wldt.event.DefaultEventLogger;
import it.unimore.dipi.iot.wldt.event.EventBus;
import it.unimore.dipi.iot.wldt.event.PhysicalEventMessage;
import it.unimore.dipi.iot.wldt.exception.EventBusException;
import it.unimore.dipi.iot.wldt.exception.ModelException;
import it.unimore.dipi.iot.wldt.exception.ModelFunctionException;
import it.unimore.dipi.iot.wldt.exception.WldtConfigurationException;
import it.unimore.dipi.iot.wldt.model.ShadowingModelFunction;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.*;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class PhysicalAdapterTester {

    private static final Logger logger = LoggerFactory.getLogger(PhysicalAdapterTester.class);

    private CountDownLatch lock = null;

    private List<PhysicalEventMessage<Double>> receivedPhysicalEventMessageList = null;

    private static final String DEMO_MQTT_BODY = "DEMO_BODY_MQTT";

    private static final String DEMO_MQTT_MESSAGE_TYPE = "mqtt.telemetry";

    private WldtConfiguration buildWldtConfiguration() throws WldtConfigurationException, ModelException {

        //Manual creation of the WldtConfiguration
        WldtConfiguration wldtConfiguration = new WldtConfiguration();
        wldtConfiguration.setDeviceNameSpace("it.unimore.dipi.things");
        wldtConfiguration.setWldtBaseIdentifier("wldt");
        wldtConfiguration.setWldtStartupTimeSeconds(10);
        wldtConfiguration.setApplicationMetricsEnabled(true);
        wldtConfiguration.setApplicationMetricsReportingPeriodSeconds(10);
        wldtConfiguration.setMetricsReporterList(Collections.singletonList("csv"));
        wldtConfiguration.setGraphitePrefix("wldt");
        wldtConfiguration.setGraphiteReporterAddress("127.0.0.1");
        wldtConfiguration.setGraphiteReporterPort(2003);

        return wldtConfiguration;
    }


    @Test
    public void testPhysicalAdapter() throws WldtConfigurationException, EventBusException, ModelException, ModelFunctionException, InterruptedException {

        this.receivedPhysicalEventMessageList = new ArrayList<>();

        lock = new CountDownLatch(DummyPhysicalAdapter.TARGET_GENERATED_MESSAGES);

        //Set EventBus Logger
        EventBus.getInstance().setEventLogger(new DefaultEventLogger());

        //Create Physical Adapter
        DummyPhysicalAdapter dummyPhysicalAdapter = new DummyPhysicalAdapter("dummy-physical-adapter", new DummyPhysicalAdapterConfiguration());

        //Init the Engine
        WldtEngine wldtEngine = new WldtEngine(new ShadowingModelFunction("test-shadowing-function") {

            @Override
            protected void onStart() {
                logger.debug("ShadowingModelFunction - onStart()");
            }

            @Override
            protected void onStop() {
                logger.debug("ShadowingModelFunction - onStop()");
            }

            @Override
            protected void onPhysicalEvent(PhysicalEventMessage<?> physicalEventMessage) {
                logger.info("onPhysicalEvent()-> {}", physicalEventMessage);

                if(physicalEventMessage != null
                        && getPhysicalEventRawTypeList().isPresent()
                        && getPhysicalEventsFilter().contains(physicalEventMessage.getType())
                        && physicalEventMessage.getBody() instanceof Double){
                    logger.info("CORRECT PhysicalEvent Received -> Type: {} Message: {}", physicalEventMessage.getType(), physicalEventMessage);
                    lock.countDown();
                    receivedPhysicalEventMessageList.add((PhysicalEventMessage<Double>) physicalEventMessage);
                }
                else
                    logger.error("WRONG Physical Event Message Received !");
            }

            @Override
            protected Optional<List<String>> getPhysicalEventRawTypeList() {
                //We use the same event type generated by the adopter Physical Adapter
                return dummyPhysicalAdapter.getGeneratedPhysicalEventTypeList();
            }
        }, buildWldtConfiguration());

        wldtEngine.addPhysicalAdapter(dummyPhysicalAdapter);
        wldtEngine.startWorkers();

        //Wait until all the messages have been received
        lock.await((DummyPhysicalAdapter.MESSAGE_SLEEP_PERIOD_MS
                        + (DummyPhysicalAdapter.TARGET_GENERATED_MESSAGES*DummyPhysicalAdapter.MESSAGE_SLEEP_PERIOD_MS)),
                TimeUnit.MILLISECONDS);

        assertNotNull(receivedPhysicalEventMessageList);
        assertEquals(DummyPhysicalAdapter.TARGET_GENERATED_MESSAGES, receivedPhysicalEventMessageList.size());

        Thread.sleep(2000);

        wldtEngine.stopWorkers();
    }

}
